version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "1234"  
      MYSQL_DATABASE: "Podcraze"   
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network

    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - .:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"  # Expose HTTPS port
    volumes:
      
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # Use absolute host path
      - ./certbot/www:/var/www/certbot:ro
      - ./media:/app/media:ro
      - ./staticfiles:/app/staticfiles:ro

      
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes: 
  db_data:
  static_volume:
  media_volume: