# Generated by Django 5.1.4 on 2025-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_offer_productimage_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_path',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
