# Generated by Django 5.1.4 on 2025-01-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_productimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked')], default='Active', max_length=10),
        ),
    ]
