# Generated by Django 5.1.4 on 2025-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
