# Generated by Django 5.1.4 on 2025-01-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
    ]
