# Generated by Django 5.1.4 on 2025-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_order_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_pending', 'Return Pending'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50),
        ),
    ]
