# Generated by Django 5.1.4 on 2025-01-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='max_uses',
        ),
    ]
