# Generated by Django 5.1.4 on 2025-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_offer_product_alter_offer_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
