# Generated by Django 5.1.4 on 2025-01-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_productvariant_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='offer_price',
        ),
    ]
