# Generated by Django 5.1.4 on 2025-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_orderitem_cancellation_reason_orderitem_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('return_pending', 'Return Pending'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected')], default='pending', max_length=50),
        ),
    ]
